# Generated by Django 4.0.4 on 2022-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='uploads/profileUserDefaultImg.png', upload_to='uploads/'),
        ),
    ]
