# Generated by Django 4.0.4 on 2022-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='uploads/profileUserDefaultImg.png', null=True, upload_to='uploads/'),
        ),
    ]
