# Generated by Django 4.0.4 on 2022-06-06 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blockedUsers',
            field=models.ManyToManyField(related_name='blockedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
