# Generated by Django 4.0.4 on 2022-06-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_profile_blockedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
